/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useEffect, useRef } from 'react'
import { useGLTF, 

useAnimations } from '@react-three/drei'


const Model =(props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/model.gltf')
const { actions, mixer } = useAnimations(animations, group)
console.log(actions)
useEffect(()=>{
    actions['course_chapeau'].play()
    mixer.timeScale = 2
},[])
  return (
    <group ref={group} {...props} dispose={null}>
<group rotation={[0, 0.01, 0,]} >
<primitive object={nodes.root} />
<skinnedMesh geometry={nodes.Chapeau.geometry} material={materials['color_main.014']} skeleton={nodes.Chapeau.skeleton} />
</group>

    </group>
  )
}
export default Model

useGLTF.preload('/models/model.gltf')
